Token Management
rart/studio-ui pull request #4
Opened 2021-01-11 15:12 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4447

2021-01-12 12:13 UTC, rart requested changes
Please

2021-01-12 12:13 UTC, rart commented on static-assets/scripts/main.js
> +      $(workarea).html('');
Seems pointless. The container is empty as it comes from the template.
Does angular keep around the view as it unmounts? If that's the case, we should be unmounting the react component too.

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +
x

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +
x

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Controls/ConfirmDropdown.tsx
> +import { IconButton } from '@material-ui/core';
Fix import

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CopyTokenDialog.tsx
> +/*
Create at it's own folder (with it's index and such)

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CreateTokenDialog.tsx
> +/*
Create at it's own folder (with it's index and such)

2021-01-12 12:13 UTC, rart commented on ui/app/src/services/token.ts
> +/*
Pluralize name (like all other services)

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +  ];
Should we memoize?

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CopyTokenDialog.tsx
> +        </Button>
Pull & use SecondaryButton; remove variant and colour props.

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CopyTokenDialog.tsx
> +        </Button>
Pull & use PrimaryButton; remove variant and colour props.

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CreateTokenDialog.tsx
> +        </Button>
Pull & use Primary/SecondaryButton components; remove variant and color props.

2021-01-12 12:13 UTC, rart commented on ui/app/src/components/Dialogs/CreateTokenDialog.tsx
> +        <Button onClick={() => onOk()} variant="contained" color="primary" autoFocus disabled={inProgress}>
```suggestion
        <PrimaryButton onClick={onOk} autoFocus disabled={inProgress}>
```

2021-01-12 16:06 UTC, aachavarria commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +  ];
I will add an useMemo

2021-01-13 13:55 UTC, rart requested changes

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +        <Link
These should be buttons (text variant)

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/CopyTokenDialog/CopyTokenDialog.tsx
> +  const tokenKey = inputRef.current;
Use the ref directly where needed.

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +} from '@material-ui/core';
Fix import

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +    }).subscribe((token) => {
Handle errors and revert

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +    deleteToken(id).subscribe((token) => {
Handle errors and revert

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +        // TODO: API to Delete many??
x

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +        forkJoin(requests).subscribe((responses) => {
Handle errors and revert list

2021-01-13 13:55 UTC, rart commented on ui/app/src/components/TokenManagement/TokenManagement.tsx
> +                            <FormattedMessage id="words.expired" defaultMessage="Expired" />
let’s store the moment/date on a car to avoid the repeated call 
Do you really need to use moment? Looks like simple dates would do

2021-01-14 08:25 UTC, rart approved these changes

2021-01-22 14:43 UTC, merged